___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___
# Plotly and Cufflinks

Plotly is a library that allows you to create interactive plots that you can use in dashboards or websites (you can save them as html files or static images).

## Installation

In order for this all to work, you'll need to install plotly and cufflinks to call plots directly off of a pandas dataframe. These libraries are not currently available through **conda** but are available through **pip**. Install the libraries at your command line/terminal using:

    pip install plotly
    pip install cufflinks

** NOTE: Make sure you only have one installation of Python on your computer when you do this, otherwise the installation may not work. **

## Imports and Set-up

In [1]:
print('hello')

hello

In [2]:
import pandas as pd
import numpy as np
%matplotlib inline

In [3]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__) # requires version >= 1.9.0

6.5.0

In [4]:
import cufflinks as cf

In [19]:
# For Notebooks
init_notebook_mode(connected=True)

In [20]:
# For offline use
cf.go_offline()

### Fake Data

In [5]:
df = pd.DataFrame(np.random.randn(100,4),columns='A B C D'.split())

In [6]:
df.head()

          A         B         C         D
0 -0.776484  2.147708  2.499240  0.838128
1  1.629547  0.523823 -0.517951  1.982859
2  0.533022 -0.683985  0.033258 -1.396052
3 -1.503920  0.216813 -1.042328  0.796332
4  0.015343  0.860398  0.590843  0.921446

In [11]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})

In [40]:
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50

## Using Cufflinks and iplot()

* scatter
* bar
* box
* spread
* ratio
* heatmap
* surface
* histogram
* bubble

## Scatter

In [7]:
import plotly.express as px

fig = px.scatter(df, x='A', y='B')
fig.show()

In [13]:
df.iplot(kind='scatter',x='A',y='B',mode='markers',size=10)

ValueError:
    Invalid value of type 'builtins.str' received for the 'color' property of scatter.line
        Received value: 'rgba(255, 153, 51, np.float64(1.0))'

    The 'color' property is a color and may be specified as:
      - A hex string (e.g. '#ff0000')
      - An rgb/rgba string (e.g. 'rgb(255,0,0)')
      - An hsl/hsla string (e.g. 'hsl(0,100%,50%)')
      - An hsv/hsva string (e.g. 'hsv(0,100%,100%)')
      - A named CSS color: see https://plotly.com/python/css-colors/ for a list

## Bar Plots

In [14]:
df2.iplot(kind='bar',x='Category',y='Values')

ValueError:
    Invalid value of type 'builtins.str' received for the 'color' property of bar.marker.line
        Received value: 'rgba(255, 153, 51, np.float64(1.0))'

    The 'color' property is a color and may be specified as:
      - A hex string (e.g. '#ff0000')
      - An rgb/rgba string (e.g. 'rgb(255,0,0)')
      - An hsl/hsla string (e.g. 'hsl(0,100%,50%)')
      - An hsv/hsva string (e.g. 'hsv(0,100%,100%)')
      - A named CSS color: see https://plotly.com/python/css-colors/ for a list
      - A number that will be interpreted as a color
        according to bar.marker.line.colorscale
      - A list or array of any of the above

In [33]:
df.count().iplot(kind='bar')

## Boxplots

In [34]:
df.iplot(kind='box')

## 3d Surface

In [8]:
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})
df3.iplot(kind='surface',colorscale='rdylbu')

Exception: chart_studio is required outside of offline mode: please run pip install chart_studio

In [10]:
import plotly.graph_objects as go
import numpy as np

# sample data
x = np.linspace(-2, 2, 50)
y = np.linspace(-2, 2, 50)
X, Y = np.meshgrid(x, y)
Z = np.sin(X**2 + Y**2)

fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y)])
fig.update_layout(title="3D Surface Plot")
fig.show()

## Spread

In [50]:
df[['A','B']].iplot(kind='spread')

## histogram

In [56]:
df['A'].iplot(kind='hist',bins=25)

In [60]:
df.iplot(kind='bubble',x='A',y='B',size='C')

## scatter_matrix()

Similar to sns.pairplot()

In [13]:
df.scatter_matrix()

# Great Job!